import type { Metadata } from "next";
import Header from "../components/header";

import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        <Header/>

        {/* Place children where you want to render a page or nested layout */}
        <main>{children}</main>
        
      </body>
    </html>
  )
}
